import type { Employee, OverlappingProject } from "./types";

// ─── SEED DATA FOR SCALE ───────────────────────────────────────────────
// 36 employees across 8 departments, 12 locations, 18+ active projects
// Simulates a slice of a 3,000-person org

const DEPARTMENTS = [
  "Engineering", "Design", "Data & Analytics", "Infrastructure",
  "Quality", "Product", "Finance", "Operations",
] as const;

const LOCATIONS = [
  "London", "Berlin", "Mumbai", "Dublin", "Tokyo", "Milan",
  "Prague", "Seoul", "Barcelona", "Copenhagen", "Cairo", "Accra",
  "New York", "São Paulo", "Singapore", "Stockholm",
] as const;

export const EMPLOYEES: Employee[] = [
  // ── Original 12 (unchanged IDs for backwards compat) ──
  {
    id: "emp-001", name: "Sarah Chen", role: "Senior Full-Stack Engineer",
    department: "Engineering",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "GraphQL"],
    availability: "available", hourlyRate: 145, location: "London",
    pastProjects: [
      { name: "API Gateway", year: 2024, role: "Architect", status: "active", priority: "critical" },
      { name: "Platform Migration v3", year: 2023, role: "Tech Lead", status: "completed", priority: "high" },
      { name: "Customer Portal Rebuild", year: 2022, role: "Senior Engineer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 8, avatarInitials: "SC",
    collaborators: ["emp-006", "emp-007", "emp-005"],
    technologies: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "GraphQL", "Docker"],
    domainExpertise: ["Platform Engineering", "API Design", "Web Applications"],
  },
  {
    id: "emp-002", name: "Marcus Rivera", role: "Product Designer",
    department: "Design",
    skills: ["Figma", "User Research", "Design Systems", "Prototyping", "Accessibility"],
    availability: "partial", hourlyRate: 130, location: "Berlin",
    pastProjects: [
      { name: "Onboarding Flow", year: 2024, role: "UX Lead", status: "active", priority: "high" },
      { name: "Design System 2.0", year: 2023, role: "Lead Designer", status: "completed", priority: "high" },
      { name: "Mobile App Redesign", year: 2022, role: "Product Designer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 7, avatarInitials: "MR",
    collaborators: ["emp-010", "emp-005", "emp-012"],
    technologies: ["Figma", "Sketch", "Framer", "Storybook"],
    domainExpertise: ["Design Systems", "Mobile UX", "Accessibility"],
  },
  {
    id: "emp-003", name: "Priya Patel", role: "Data Scientist",
    department: "Data & Analytics",
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow", "Data Visualization", "Statistics"],
    availability: "available", hourlyRate: 155, location: "Mumbai",
    pastProjects: [
      { name: "Analytics Dashboard", year: 2024, role: "Technical Lead", status: "active", priority: "critical" },
      { name: "Recommendation Engine", year: 2023, role: "Lead Data Scientist", status: "completed", priority: "high" },
      { name: "Churn Prediction Model", year: 2022, role: "Data Scientist", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "lead", yearsExperience: 10, avatarInitials: "PP",
    collaborators: ["emp-009", "emp-005"],
    technologies: ["Python", "TensorFlow", "SQL", "Spark", "Tableau", "dbt"],
    domainExpertise: ["Machine Learning", "Data Engineering", "Analytics"],
  },
  {
    id: "emp-004", name: "James O'Brien", role: "DevOps Engineer",
    department: "Infrastructure",
    skills: ["Kubernetes", "Docker", "Terraform", "AWS", "CI/CD", "Monitoring"],
    availability: "partial", hourlyRate: 140, location: "Dublin",
    pastProjects: [
      { name: "Observability Stack", year: 2024, role: "Technical Lead", status: "active", priority: "high" },
      { name: "Cloud Migration", year: 2023, role: "Infrastructure Lead", status: "completed", priority: "critical" },
      { name: "Zero-Downtime Deploy Pipeline", year: 2022, role: "DevOps Engineer", status: "completed", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 6, avatarInitials: "JO",
    collaborators: ["emp-011", "emp-007"],
    technologies: ["Kubernetes", "Docker", "Terraform", "AWS", "Datadog", "ArgoCD"],
    domainExpertise: ["Cloud Infrastructure", "CI/CD", "Observability"],
  },
  {
    id: "emp-005", name: "Yuki Tanaka", role: "Frontend Engineer",
    department: "Engineering",
    skills: ["React", "TypeScript", "CSS", "Animation", "Performance", "Testing"],
    availability: "available", hourlyRate: 120, location: "Tokyo",
    pastProjects: [
      { name: "Performance Optimization Sprint", year: 2024, role: "Lead", status: "active", priority: "high" },
      { name: "Component Library", year: 2023, role: "Frontend Engineer", status: "completed", priority: "medium" },
      { name: "Dashboard v2", year: 2022, role: "Frontend Engineer", status: "completed", priority: "low" },
    ],
    seniorityLevel: "mid", yearsExperience: 4, avatarInitials: "YT",
    collaborators: ["emp-001", "emp-002"],
    technologies: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Vitest"],
    domainExpertise: ["Frontend Performance", "Component Architecture", "Animation"],
  },
  {
    id: "emp-006", name: "Amara Osei", role: "Engineering Manager",
    department: "Engineering",
    skills: ["Project Management", "Agile", "Technical Architecture", "Stakeholder Management", "Mentoring"],
    availability: "committed", hourlyRate: 170, location: "Accra",
    pastProjects: [
      { name: "Process Overhaul", year: 2024, role: "Manager", status: "active", priority: "high" },
      { name: "Platform Migration v3", year: 2023, role: "Engineering Manager", status: "completed", priority: "critical" },
      { name: "Team Scaling Initiative", year: 2022, role: "Program Lead", status: "completed", priority: "high" },
    ],
    seniorityLevel: "lead", yearsExperience: 12, avatarInitials: "AO",
    collaborators: ["emp-001", "emp-007", "emp-008"],
    technologies: ["Jira", "Confluence", "Linear"],
    domainExpertise: ["Team Leadership", "Agile Delivery", "Organisational Design"],
  },
  {
    id: "emp-007", name: "Leo Martinelli", role: "Backend Engineer",
    department: "Engineering",
    skills: ["Go", "Microservices", "PostgreSQL", "Redis", "gRPC", "Event-Driven Architecture"],
    availability: "available", hourlyRate: 135, location: "Milan",
    pastProjects: [
      { name: "Event Bus Implementation", year: 2024, role: "Technical Lead", status: "active", priority: "critical" },
      { name: "Payment Service Rewrite", year: 2023, role: "Backend Engineer", status: "completed", priority: "high" },
      { name: "API Gateway", year: 2022, role: "Backend Engineer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 7, avatarInitials: "LM",
    collaborators: ["emp-001", "emp-004", "emp-006"],
    technologies: ["Go", "PostgreSQL", "Redis", "Kafka", "gRPC", "Docker"],
    domainExpertise: ["Microservices", "Event Systems", "API Design"],
  },
  {
    id: "emp-008", name: "Nina Volkov", role: "QA Lead",
    department: "Quality",
    skills: ["Test Automation", "Cypress", "Performance Testing", "Security Testing", "CI/CD"],
    availability: "partial", hourlyRate: 115, location: "Prague",
    pastProjects: [
      { name: "Load Testing Suite", year: 2024, role: "Performance Engineer", status: "active", priority: "high" },
      { name: "E2E Test Framework", year: 2023, role: "QA Lead", status: "completed", priority: "high" },
      { name: "Security Audit Q4", year: 2022, role: "QA Engineer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "lead", yearsExperience: 9, avatarInitials: "NV",
    collaborators: ["emp-006", "emp-011"],
    technologies: ["Cypress", "Playwright", "k6", "Jest", "Selenium"],
    domainExpertise: ["Test Strategy", "Performance Engineering", "Security Testing"],
  },
  {
    id: "emp-009", name: "David Kim", role: "ML Engineer",
    department: "Data & Analytics",
    skills: ["Python", "PyTorch", "MLOps", "NLP", "Computer Vision", "AWS SageMaker"],
    availability: "available", hourlyRate: 160, location: "Seoul",
    pastProjects: [
      { name: "Image Classification Service", year: 2024, role: "Lead ML Engineer", status: "active", priority: "critical" },
      { name: "NLP Pipeline", year: 2023, role: "ML Engineer", status: "completed", priority: "high" },
      { name: "Model Serving Infrastructure", year: 2022, role: "ML Engineer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 6, avatarInitials: "DK",
    collaborators: ["emp-003"],
    technologies: ["Python", "PyTorch", "SageMaker", "MLflow", "Docker"],
    domainExpertise: ["NLP", "Computer Vision", "MLOps"],
  },
  {
    id: "emp-010", name: "Elena Rodriguez", role: "UX Researcher",
    department: "Design",
    skills: ["User Research", "Usability Testing", "Survey Design", "Data Analysis", "Workshop Facilitation"],
    availability: "available", hourlyRate: 125, location: "Barcelona",
    pastProjects: [
      { name: "Onboarding Flow", year: 2024, role: "UX Researcher", status: "active", priority: "high" },
      { name: "Voice of Customer Program", year: 2023, role: "Lead Researcher", status: "completed", priority: "high" },
      { name: "Accessibility Audit", year: 2022, role: "Researcher", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "mid", yearsExperience: 5, avatarInitials: "ER",
    collaborators: ["emp-002", "emp-012"],
    technologies: ["Maze", "Hotjar", "UserTesting", "Dovetail"],
    domainExpertise: ["User Research", "Accessibility", "Information Architecture"],
  },
  {
    id: "emp-011", name: "Omar Hassan", role: "Security Engineer",
    department: "Infrastructure",
    skills: ["Security Architecture", "Penetration Testing", "OWASP", "IAM", "Compliance", "Encryption"],
    availability: "partial", hourlyRate: 165, location: "Cairo",
    pastProjects: [
      { name: "Zero Trust Implementation", year: 2024, role: "Security Architect", status: "active", priority: "critical" },
      { name: "SOC2 Compliance", year: 2023, role: "Security Lead", status: "completed", priority: "critical" },
      { name: "Security Audit Q4", year: 2022, role: "Pen Tester", status: "completed", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 8, avatarInitials: "OH",
    collaborators: ["emp-004", "emp-008"],
    technologies: ["Vault", "AWS IAM", "Burp Suite", "Snyk", "Terraform"],
    domainExpertise: ["Security Architecture", "Compliance", "Zero Trust"],
  },
  {
    id: "emp-012", name: "Freya Andersen", role: "Technical Writer",
    department: "Product",
    skills: ["Technical Writing", "API Documentation", "Developer Experience", "Content Strategy"],
    availability: "available", hourlyRate: 95, location: "Copenhagen",
    pastProjects: [
      { name: "Developer Portal", year: 2024, role: "Content Strategist", status: "active", priority: "high" },
      { name: "API Docs Overhaul", year: 2023, role: "Lead Writer", status: "completed", priority: "medium" },
      { name: "Internal Wiki Migration", year: 2022, role: "Technical Writer", status: "completed", priority: "low" },
    ],
    seniorityLevel: "mid", yearsExperience: 4, avatarInitials: "FA",
    collaborators: ["emp-002", "emp-010"],
    technologies: ["Markdown", "Docusaurus", "Notion", "Confluence"],
    domainExpertise: ["API Documentation", "Developer Experience", "Knowledge Management"],
  },

  // ── Scaled employees (13–36) ──
  {
    id: "emp-013", name: "Raj Kapoor", role: "Platform Architect",
    department: "Engineering",
    skills: ["System Design", "AWS", "Microservices", "Java", "Kafka", "Leadership"],
    availability: "committed", hourlyRate: 185, location: "Mumbai",
    pastProjects: [
      { name: "Core Banking Modernisation", year: 2024, role: "Architect", status: "active", priority: "critical" },
      { name: "Platform Migration v3", year: 2023, role: "Consulting Architect", status: "completed", priority: "high" },
    ],
    seniorityLevel: "principal", yearsExperience: 15, avatarInitials: "RK",
    collaborators: ["emp-001", "emp-006", "emp-007"],
    technologies: ["Java", "AWS", "Kafka", "Kubernetes", "Terraform"],
    domainExpertise: ["Platform Architecture", "Distributed Systems", "Technical Strategy"],
  },
  {
    id: "emp-014", name: "Lena Johansson", role: "Product Manager",
    department: "Product",
    skills: ["Product Strategy", "Roadmapping", "User Stories", "Analytics", "Stakeholder Management"],
    availability: "available", hourlyRate: 150, location: "Stockholm",
    pastProjects: [
      { name: "Payments v2", year: 2024, role: "Product Lead", status: "active", priority: "critical" },
      { name: "Onboarding Flow", year: 2023, role: "PM", status: "completed", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 9, avatarInitials: "LJ",
    collaborators: ["emp-002", "emp-012", "emp-015"],
    technologies: ["Amplitude", "Mixpanel", "Linear", "Notion"],
    domainExpertise: ["Product Strategy", "Growth", "Fintech"],
  },
  {
    id: "emp-015", name: "Chen Wei", role: "iOS Engineer",
    department: "Engineering",
    skills: ["Swift", "SwiftUI", "Objective-C", "Core Data", "CI/CD", "ARKit"],
    availability: "available", hourlyRate: 140, location: "Singapore",
    pastProjects: [
      { name: "Mobile App v4", year: 2024, role: "iOS Lead", status: "active", priority: "high" },
      { name: "Mobile App Redesign", year: 2022, role: "iOS Engineer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 7, avatarInitials: "CW",
    collaborators: ["emp-016", "emp-002"],
    technologies: ["Swift", "SwiftUI", "Xcode", "Firebase", "Fastlane"],
    domainExpertise: ["iOS Development", "Mobile Architecture", "AR/VR"],
  },
  {
    id: "emp-016", name: "Aisha Mohammed", role: "Android Engineer",
    department: "Engineering",
    skills: ["Kotlin", "Jetpack Compose", "Android SDK", "Firebase", "CI/CD"],
    availability: "partial", hourlyRate: 135, location: "Dubai",
    pastProjects: [
      { name: "Mobile App v4", year: 2024, role: "Android Lead", status: "active", priority: "high" },
      { name: "Push Notification Service", year: 2023, role: "Mobile Engineer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 6, avatarInitials: "AM",
    collaborators: ["emp-015", "emp-007"],
    technologies: ["Kotlin", "Jetpack Compose", "Firebase", "Gradle", "Room"],
    domainExpertise: ["Android Development", "Mobile Architecture", "Push Systems"],
  },
  {
    id: "emp-017", name: "Thomas Müller", role: "Data Engineer",
    department: "Data & Analytics",
    skills: ["Python", "Spark", "Airflow", "dbt", "SQL", "Data Modelling"],
    availability: "available", hourlyRate: 145, location: "Berlin",
    pastProjects: [
      { name: "Data Lake Migration", year: 2024, role: "Lead Data Engineer", status: "active", priority: "critical" },
      { name: "ETL Pipeline Consolidation", year: 2023, role: "Data Engineer", status: "completed", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 8, avatarInitials: "TM",
    collaborators: ["emp-003", "emp-009"],
    technologies: ["Python", "Spark", "Airflow", "dbt", "Snowflake", "BigQuery"],
    domainExpertise: ["Data Engineering", "Data Modelling", "ETL"],
  },
  {
    id: "emp-018", name: "Sofia Costa", role: "Brand Designer",
    department: "Design",
    skills: ["Brand Identity", "Typography", "Illustration", "Motion Graphics", "Art Direction"],
    availability: "available", hourlyRate: 120, location: "São Paulo",
    pastProjects: [
      { name: "Brand Refresh 2024", year: 2024, role: "Art Director", status: "active", priority: "high" },
      { name: "Marketing Collateral System", year: 2023, role: "Designer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "mid", yearsExperience: 5, avatarInitials: "SoC",
    collaborators: ["emp-002", "emp-010"],
    technologies: ["Illustrator", "After Effects", "Figma", "Cinema 4D"],
    domainExpertise: ["Brand Design", "Visual Identity", "Motion"],
  },
  {
    id: "emp-019", name: "Henrik Nilsson", role: "SRE",
    department: "Infrastructure",
    skills: ["Incident Response", "SLO/SLI", "Prometheus", "Grafana", "On-Call", "Chaos Engineering"],
    availability: "partial", hourlyRate: 155, location: "Stockholm",
    pastProjects: [
      { name: "SRE Maturity Programme", year: 2024, role: "SRE Lead", status: "active", priority: "high" },
      { name: "Observability Stack", year: 2024, role: "SRE", status: "active", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 7, avatarInitials: "HN",
    collaborators: ["emp-004", "emp-011"],
    technologies: ["Prometheus", "Grafana", "PagerDuty", "Terraform", "Go"],
    domainExpertise: ["Site Reliability", "Incident Management", "Chaos Engineering"],
  },
  {
    id: "emp-020", name: "Marie Dupont", role: "Finance Analyst",
    department: "Finance",
    skills: ["Financial Modelling", "Excel", "SQL", "Forecasting", "Budgeting", "Tableau"],
    availability: "available", hourlyRate: 110, location: "London",
    pastProjects: [
      { name: "Budget Planning Tool", year: 2024, role: "Lead Analyst", status: "active", priority: "high" },
      { name: "Cost Centre Consolidation", year: 2023, role: "Analyst", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "mid", yearsExperience: 5, avatarInitials: "MD",
    collaborators: ["emp-021", "emp-003"],
    technologies: ["Excel", "Tableau", "SQL", "Power BI"],
    domainExpertise: ["Financial Planning", "Budgeting", "Reporting"],
  },
  {
    id: "emp-021", name: "Richard Okonkwo", role: "Finance Director",
    department: "Finance",
    skills: ["Strategic Finance", "Board Reporting", "M&A", "Risk Management", "Compliance"],
    availability: "committed", hourlyRate: 200, location: "London",
    pastProjects: [
      { name: "Annual Audit 2024", year: 2024, role: "Director", status: "active", priority: "critical" },
      { name: "Budget Planning Tool", year: 2024, role: "Sponsor", status: "active", priority: "high" },
    ],
    seniorityLevel: "principal", yearsExperience: 18, avatarInitials: "RO",
    collaborators: ["emp-020", "emp-006"],
    technologies: ["SAP", "Oracle Financials", "Tableau"],
    domainExpertise: ["Strategic Finance", "Corporate Governance", "Risk"],
  },
  {
    id: "emp-022", name: "Kenji Watanabe", role: "Backend Engineer",
    department: "Engineering",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Microservices", "Kafka"],
    availability: "available", hourlyRate: 130, location: "Tokyo",
    pastProjects: [
      { name: "Core Banking Modernisation", year: 2024, role: "Senior Engineer", status: "active", priority: "critical" },
      { name: "Payment Service Rewrite", year: 2023, role: "Engineer", status: "completed", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 6, avatarInitials: "KW",
    collaborators: ["emp-007", "emp-013"],
    technologies: ["Java", "Spring Boot", "PostgreSQL", "Kafka", "Redis"],
    domainExpertise: ["Banking Systems", "Payments", "Backend"],
  },
  {
    id: "emp-023", name: "Fatima Al-Rashidi", role: "QA Engineer",
    department: "Quality",
    skills: ["Manual Testing", "Regression Testing", "API Testing", "Postman", "JIRA"],
    availability: "available", hourlyRate: 90, location: "Dubai",
    pastProjects: [
      { name: "Payments v2", year: 2024, role: "QA Engineer", status: "active", priority: "critical" },
      { name: "Mobile App v4", year: 2024, role: "QA Engineer", status: "active", priority: "high" },
    ],
    seniorityLevel: "mid", yearsExperience: 4, avatarInitials: "FA",
    collaborators: ["emp-008", "emp-016"],
    technologies: ["Postman", "JIRA", "TestRail", "Charles Proxy"],
    domainExpertise: ["Mobile Testing", "API Testing", "Payment Flows"],
  },
  {
    id: "emp-024", name: "Anna Kowalski", role: "Operations Manager",
    department: "Operations",
    skills: ["Process Design", "Vendor Management", "Procurement", "Lean", "Six Sigma"],
    availability: "partial", hourlyRate: 125, location: "Prague",
    pastProjects: [
      { name: "Vendor Consolidation", year: 2024, role: "Project Lead", status: "active", priority: "high" },
      { name: "Office Relocation Programme", year: 2023, role: "Operations Lead", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 9, avatarInitials: "AK",
    collaborators: ["emp-021", "emp-006"],
    technologies: ["SAP", "Asana", "Monday.com"],
    domainExpertise: ["Operations", "Procurement", "Process Improvement"],
  },
  {
    id: "emp-025", name: "Samuel Adebayo", role: "Frontend Engineer",
    department: "Engineering",
    skills: ["React", "Next.js", "TypeScript", "GraphQL", "Accessibility", "Testing"],
    availability: "available", hourlyRate: 115, location: "Accra",
    pastProjects: [
      { name: "Customer Portal Rebuild", year: 2024, role: "Frontend Engineer", status: "active", priority: "high" },
      { name: "Dashboard v2", year: 2023, role: "Junior Engineer", status: "completed", priority: "low" },
    ],
    seniorityLevel: "mid", yearsExperience: 3, avatarInitials: "SA",
    collaborators: ["emp-005", "emp-001"],
    technologies: ["React", "Next.js", "TypeScript", "GraphQL", "Storybook"],
    domainExpertise: ["Web Applications", "Accessibility", "Component Architecture"],
  },
  {
    id: "emp-026", name: "Mika Virtanen", role: "Cloud Architect",
    department: "Infrastructure",
    skills: ["AWS", "Azure", "GCP", "Terraform", "Networking", "Cost Optimisation"],
    availability: "available", hourlyRate: 175, location: "Stockholm",
    pastProjects: [
      { name: "Multi-Cloud Strategy", year: 2024, role: "Lead Architect", status: "active", priority: "critical" },
      { name: "Cloud Migration", year: 2023, role: "Cloud Architect", status: "completed", priority: "critical" },
    ],
    seniorityLevel: "principal", yearsExperience: 14, avatarInitials: "MV",
    collaborators: ["emp-004", "emp-019", "emp-013"],
    technologies: ["AWS", "Azure", "Terraform", "CloudFormation", "CDK"],
    domainExpertise: ["Cloud Architecture", "Cost Optimisation", "Multi-Cloud"],
  },
  {
    id: "emp-027", name: "Isabella Rossi", role: "Content Designer",
    department: "Design",
    skills: ["UX Writing", "Content Strategy", "Microcopy", "Localisation", "Voice & Tone"],
    availability: "available", hourlyRate: 105, location: "Milan",
    pastProjects: [
      { name: "Onboarding Flow", year: 2024, role: "Content Designer", status: "active", priority: "high" },
      { name: "Error Message Overhaul", year: 2023, role: "UX Writer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "mid", yearsExperience: 4, avatarInitials: "IR",
    collaborators: ["emp-002", "emp-012", "emp-010"],
    technologies: ["Figma", "Phrase", "Lokalise", "Notion"],
    domainExpertise: ["UX Writing", "Localisation", "Content Systems"],
  },
  {
    id: "emp-028", name: "Jorge Mendes", role: "Scrum Master",
    department: "Product",
    skills: ["Scrum", "Kanban", "Facilitation", "Conflict Resolution", "Coaching"],
    availability: "partial", hourlyRate: 110, location: "São Paulo",
    pastProjects: [
      { name: "Agile Transformation", year: 2024, role: "Lead Scrum Master", status: "active", priority: "high" },
      { name: "Process Overhaul", year: 2024, role: "Scrum Master", status: "active", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 8, avatarInitials: "JM",
    collaborators: ["emp-006", "emp-014"],
    technologies: ["Jira", "Miro", "Linear", "Retrium"],
    domainExpertise: ["Agile Coaching", "Team Health", "Process Design"],
  },
  {
    id: "emp-029", name: "Nadia Petrova", role: "Data Analyst",
    department: "Data & Analytics",
    skills: ["SQL", "Python", "Tableau", "Excel", "Data Visualization", "Reporting"],
    availability: "available", hourlyRate: 100, location: "Prague",
    pastProjects: [
      { name: "Executive Reporting Dashboard", year: 2024, role: "Lead Analyst", status: "active", priority: "high" },
      { name: "Analytics Dashboard", year: 2023, role: "Analyst", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "mid", yearsExperience: 4, avatarInitials: "NP",
    collaborators: ["emp-003", "emp-020"],
    technologies: ["SQL", "Python", "Tableau", "Looker", "dbt"],
    domainExpertise: ["Business Intelligence", "Executive Reporting", "Data Viz"],
  },
  {
    id: "emp-030", name: "Daniel Akpan", role: "Network Engineer",
    department: "Infrastructure",
    skills: ["Networking", "Firewalls", "VPN", "DNS", "Load Balancing", "SDN"],
    availability: "committed", hourlyRate: 130, location: "London",
    pastProjects: [
      { name: "Network Refresh Programme", year: 2024, role: "Lead Engineer", status: "active", priority: "critical" },
      { name: "Office Relocation Programme", year: 2023, role: "Network Engineer", status: "completed", priority: "medium" },
    ],
    seniorityLevel: "senior", yearsExperience: 10, avatarInitials: "DA",
    collaborators: ["emp-004", "emp-026"],
    technologies: ["Cisco", "Palo Alto", "F5", "Cloudflare", "Terraform"],
    domainExpertise: ["Networking", "Security", "CDN"],
  },
  {
    id: "emp-031", name: "Lisa Chang", role: "Product Analyst",
    department: "Product",
    skills: ["Product Analytics", "SQL", "Amplitude", "A/B Testing", "User Segmentation"],
    availability: "available", hourlyRate: 115, location: "Singapore",
    pastProjects: [
      { name: "Conversion Funnel Optimisation", year: 2024, role: "Lead Analyst", status: "active", priority: "high" },
      { name: "Payments v2", year: 2024, role: "Analyst", status: "active", priority: "critical" },
    ],
    seniorityLevel: "mid", yearsExperience: 5, avatarInitials: "LC",
    collaborators: ["emp-014", "emp-003"],
    technologies: ["Amplitude", "SQL", "Looker", "Mixpanel"],
    domainExpertise: ["Product Analytics", "Experimentation", "Growth"],
  },
  {
    id: "emp-032", name: "Erik Lindberg", role: "Compliance Officer",
    department: "Operations",
    skills: ["GDPR", "Regulatory Compliance", "Risk Assessment", "Audit", "Policy"],
    availability: "partial", hourlyRate: 140, location: "Stockholm",
    pastProjects: [
      { name: "GDPR Remediation Phase 2", year: 2024, role: "Lead", status: "active", priority: "critical" },
      { name: "SOC2 Compliance", year: 2023, role: "Compliance Advisor", status: "completed", priority: "critical" },
    ],
    seniorityLevel: "senior", yearsExperience: 11, avatarInitials: "EL",
    collaborators: ["emp-011", "emp-021"],
    technologies: ["OneTrust", "ServiceNow", "Vanta"],
    domainExpertise: ["GDPR", "SOC2", "Regulatory Compliance"],
  },
  {
    id: "emp-033", name: "Mei Lin Tan", role: "Frontend Engineer",
    department: "Engineering",
    skills: ["Vue.js", "TypeScript", "CSS", "Web Components", "Accessibility"],
    availability: "available", hourlyRate: 125, location: "Singapore",
    pastProjects: [
      { name: "Internal Tools Revamp", year: 2024, role: "Frontend Lead", status: "active", priority: "medium" },
      { name: "Design System 2.0", year: 2023, role: "Frontend Engineer", status: "completed", priority: "high" },
    ],
    seniorityLevel: "mid", yearsExperience: 5, avatarInitials: "ML",
    collaborators: ["emp-005", "emp-002"],
    technologies: ["Vue.js", "TypeScript", "Vite", "Storybook", "Tailwind CSS"],
    domainExpertise: ["Frontend Architecture", "Design Systems", "Internal Tools"],
  },
  {
    id: "emp-034", name: "Carlos Mendoza", role: "Solutions Architect",
    department: "Engineering",
    skills: ["System Integration", "Enterprise Architecture", "API Design", "Documentation", "Consulting"],
    availability: "partial", hourlyRate: 165, location: "New York",
    pastProjects: [
      { name: "Enterprise Integration Hub", year: 2024, role: "Solutions Architect", status: "active", priority: "critical" },
      { name: "API Gateway", year: 2024, role: "Advisor", status: "active", priority: "critical" },
    ],
    seniorityLevel: "principal", yearsExperience: 16, avatarInitials: "CM",
    collaborators: ["emp-001", "emp-013", "emp-007"],
    technologies: ["MuleSoft", "AWS", "GraphQL", "REST", "gRPC"],
    domainExpertise: ["Enterprise Integration", "API Strategy", "Technical Consulting"],
  },
  {
    id: "emp-035", name: "Yara Benali", role: "People Partner",
    department: "Operations",
    skills: ["HR Strategy", "Performance Management", "Culture", "Talent Acquisition", "L&D"],
    availability: "available", hourlyRate: 120, location: "Cairo",
    pastProjects: [
      { name: "Performance Review Redesign", year: 2024, role: "HR Lead", status: "active", priority: "high" },
      { name: "Team Scaling Initiative", year: 2022, role: "HR Partner", status: "completed", priority: "high" },
    ],
    seniorityLevel: "senior", yearsExperience: 8, avatarInitials: "YB",
    collaborators: ["emp-006", "emp-024"],
    technologies: ["BambooHR", "Lattice", "Greenhouse"],
    domainExpertise: ["People Ops", "Culture", "Talent Development"],
  },
  {
    id: "emp-036", name: "Patrick O'Sullivan", role: "Technical Program Manager",
    department: "Product",
    skills: ["Program Management", "Cross-functional Coordination", "Risk Management", "Reporting", "Agile"],
    availability: "committed", hourlyRate: 155, location: "Dublin",
    pastProjects: [
      { name: "Platform Migration v3", year: 2024, role: "TPM", status: "active", priority: "critical" },
      { name: "Core Banking Modernisation", year: 2024, role: "TPM", status: "active", priority: "critical" },
    ],
    seniorityLevel: "lead", yearsExperience: 12, avatarInitials: "PO",
    collaborators: ["emp-006", "emp-013", "emp-001"],
    technologies: ["Jira", "Confluence", "Linear", "Notion", "Airtable"],
    domainExpertise: ["Program Management", "Technical Delivery", "Stakeholder Management"],
  },
];

export const OVERLAPPING_PROJECTS: OverlappingProject[] = [
  {
    id: "overlap-001",
    name: "Finance Ops Automation",
    year: 2022,
    department: "Finance × Engineering",
    outcome: "completed",
    learnings: [
      "Built a shared data pipeline between finance and product analytics teams",
      "Established cross-functional standup cadence that reduced blockers by 40%",
      "Created reusable API integration patterns now used by 3 other teams",
    ],
    peopleInvolved: ["emp-001", "emp-003", "emp-007"],
    estimatedTimeSaved: "3 weeks",
  },
  {
    id: "overlap-002",
    name: "Platform Consolidation",
    year: 2023,
    department: "Platform Team",
    outcome: "stalled",
    learnings: [
      "Scope creep caused timeline to double — original brief was too broad",
      "Successfully migrated 2 of 5 planned services before pause",
      "Identified key dependency on legacy auth system that needs resolution",
    ],
    peopleInvolved: ["emp-001", "emp-004", "emp-006"],
    estimatedTimeSaved: "2 weeks",
  },
];
