import type { Employee, OverlappingProject } from "./types";

export const EMPLOYEES: Employee[] = [
  {
    id: "emp-001", name: "Sarah Chen", role: "Senior Full-Stack Engineer",
    department: "Engineering",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "GraphQL"],
    availability: "available", hourlyRate: 145, location: "London",
    pastProjects: [
      { name: "Platform Migration v3", year: 2023, role: "Tech Lead" },
      { name: "Customer Portal Rebuild", year: 2022, role: "Senior Engineer" },
      { name: "API Gateway", year: 2024, role: "Architect" },
    ],
    seniorityLevel: "senior", yearsExperience: 8, avatarInitials: "SC",
    collaborators: ["emp-006", "emp-007", "emp-005"],
    technologies: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "GraphQL", "Docker"],
    domainExpertise: ["Platform Engineering", "API Design", "Web Applications"],
  },
  {
    id: "emp-002", name: "Marcus Rivera", role: "Product Designer",
    department: "Design",
    skills: ["Figma", "User Research", "Design Systems", "Prototyping", "Accessibility"],
    availability: "partial", hourlyRate: 130, location: "Berlin",
    pastProjects: [
      { name: "Design System 2.0", year: 2023, role: "Lead Designer" },
      { name: "Mobile App Redesign", year: 2022, role: "Product Designer" },
      { name: "Onboarding Flow", year: 2024, role: "UX Lead" },
    ],
    seniorityLevel: "senior", yearsExperience: 7, avatarInitials: "MR",
    collaborators: ["emp-010", "emp-005", "emp-012"],
    technologies: ["Figma", "Sketch", "Framer", "Storybook"],
    domainExpertise: ["Design Systems", "Mobile UX", "Accessibility"],
  },
  {
    id: "emp-003", name: "Priya Patel", role: "Data Scientist",
    department: "Data & Analytics",
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow", "Data Visualization", "Statistics"],
    availability: "available", hourlyRate: 155, location: "Mumbai",
    pastProjects: [
      { name: "Recommendation Engine", year: 2023, role: "Lead Data Scientist" },
      { name: "Churn Prediction Model", year: 2022, role: "Data Scientist" },
      { name: "Analytics Dashboard", year: 2024, role: "Technical Lead" },
    ],
    seniorityLevel: "lead", yearsExperience: 10, avatarInitials: "PP",
    collaborators: ["emp-009", "emp-005"],
    technologies: ["Python", "TensorFlow", "SQL", "Spark", "Tableau", "dbt"],
    domainExpertise: ["Machine Learning", "Data Engineering", "Analytics"],
  },
  {
    id: "emp-004", name: "James O'Brien", role: "DevOps Engineer",
    department: "Infrastructure",
    skills: ["Kubernetes", "Docker", "Terraform", "AWS", "CI/CD", "Monitoring"],
    availability: "partial", hourlyRate: 140, location: "Dublin",
    pastProjects: [
      { name: "Cloud Migration", year: 2023, role: "Infrastructure Lead" },
      { name: "Zero-Downtime Deploy Pipeline", year: 2022, role: "DevOps Engineer" },
      { name: "Observability Stack", year: 2024, role: "Technical Lead" },
    ],
    seniorityLevel: "senior", yearsExperience: 6, avatarInitials: "JO",
    collaborators: ["emp-011", "emp-007"],
    technologies: ["Kubernetes", "Docker", "Terraform", "AWS", "Datadog", "ArgoCD"],
    domainExpertise: ["Cloud Infrastructure", "CI/CD", "Observability"],
  },
  {
    id: "emp-005", name: "Yuki Tanaka", role: "Frontend Engineer",
    department: "Engineering",
    skills: ["React", "TypeScript", "CSS", "Animation", "Performance", "Testing"],
    availability: "available", hourlyRate: 120, location: "Tokyo",
    pastProjects: [
      { name: "Component Library", year: 2023, role: "Frontend Engineer" },
      { name: "Performance Optimization Sprint", year: 2024, role: "Lead" },
      { name: "Dashboard v2", year: 2022, role: "Frontend Engineer" },
    ],
    seniorityLevel: "mid", yearsExperience: 4, avatarInitials: "YT",
    collaborators: ["emp-001", "emp-002"],
    technologies: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Vitest"],
    domainExpertise: ["Frontend Performance", "Component Architecture", "Animation"],
  },
  {
    id: "emp-006", name: "Amara Osei", role: "Engineering Manager",
    department: "Engineering",
    skills: ["Project Management", "Agile", "Technical Architecture", "Stakeholder Management", "Mentoring"],
    availability: "committed", hourlyRate: 170, location: "Accra",
    pastProjects: [
      { name: "Platform Migration v3", year: 2023, role: "Engineering Manager" },
      { name: "Team Scaling Initiative", year: 2022, role: "Program Lead" },
      { name: "Process Overhaul", year: 2024, role: "Manager" },
    ],
    seniorityLevel: "lead", yearsExperience: 12, avatarInitials: "AO",
    collaborators: ["emp-001", "emp-007", "emp-008"],
    technologies: ["Jira", "Confluence", "Linear"],
    domainExpertise: ["Team Leadership", "Agile Delivery", "Organisational Design"],
  },
  {
    id: "emp-007", name: "Leo Martinelli", role: "Backend Engineer",
    department: "Engineering",
    skills: ["Go", "Microservices", "PostgreSQL", "Redis", "gRPC", "Event-Driven Architecture"],
    availability: "available", hourlyRate: 135, location: "Milan",
    pastProjects: [
      { name: "Payment Service Rewrite", year: 2023, role: "Backend Engineer" },
      { name: "Event Bus Implementation", year: 2024, role: "Technical Lead" },
      { name: "API Gateway", year: 2022, role: "Backend Engineer" },
    ],
    seniorityLevel: "senior", yearsExperience: 7, avatarInitials: "LM",
    collaborators: ["emp-001", "emp-004", "emp-006"],
    technologies: ["Go", "PostgreSQL", "Redis", "Kafka", "gRPC", "Docker"],
    domainExpertise: ["Microservices", "Event Systems", "API Design"],
  },
  {
    id: "emp-008", name: "Nina Volkov", role: "QA Lead",
    department: "Quality",
    skills: ["Test Automation", "Cypress", "Performance Testing", "Security Testing", "CI/CD"],
    availability: "partial", hourlyRate: 115, location: "Prague",
    pastProjects: [
      { name: "E2E Test Framework", year: 2023, role: "QA Lead" },
      { name: "Load Testing Suite", year: 2024, role: "Performance Engineer" },
      { name: "Security Audit Q4", year: 2022, role: "QA Engineer" },
    ],
    seniorityLevel: "lead", yearsExperience: 9, avatarInitials: "NV",
    collaborators: ["emp-006", "emp-011"],
    technologies: ["Cypress", "Playwright", "k6", "Jest", "Selenium"],
    domainExpertise: ["Test Strategy", "Performance Engineering", "Security Testing"],
  },
  {
    id: "emp-009", name: "David Kim", role: "ML Engineer",
    department: "Data & Analytics",
    skills: ["Python", "PyTorch", "MLOps", "NLP", "Computer Vision", "AWS SageMaker"],
    availability: "available", hourlyRate: 160, location: "Seoul",
    pastProjects: [
      { name: "NLP Pipeline", year: 2023, role: "ML Engineer" },
      { name: "Image Classification Service", year: 2024, role: "Lead ML Engineer" },
      { name: "Model Serving Infrastructure", year: 2022, role: "ML Engineer" },
    ],
    seniorityLevel: "senior", yearsExperience: 6, avatarInitials: "DK",
    collaborators: ["emp-003"],
    technologies: ["Python", "PyTorch", "SageMaker", "MLflow", "Docker"],
    domainExpertise: ["NLP", "Computer Vision", "MLOps"],
  },
  {
    id: "emp-010", name: "Elena Rodriguez", role: "UX Researcher",
    department: "Design",
    skills: ["User Research", "Usability Testing", "Survey Design", "Data Analysis", "Workshop Facilitation"],
    availability: "available", hourlyRate: 125, location: "Barcelona",
    pastProjects: [
      { name: "Voice of Customer Program", year: 2023, role: "Lead Researcher" },
      { name: "Onboarding Flow", year: 2024, role: "UX Researcher" },
      { name: "Accessibility Audit", year: 2022, role: "Researcher" },
    ],
    seniorityLevel: "mid", yearsExperience: 5, avatarInitials: "ER",
    collaborators: ["emp-002", "emp-012"],
    technologies: ["Maze", "Hotjar", "UserTesting", "Dovetail"],
    domainExpertise: ["User Research", "Accessibility", "Information Architecture"],
  },
  {
    id: "emp-011", name: "Omar Hassan", role: "Security Engineer",
    department: "Infrastructure",
    skills: ["Security Architecture", "Penetration Testing", "OWASP", "IAM", "Compliance", "Encryption"],
    availability: "partial", hourlyRate: 165, location: "Cairo",
    pastProjects: [
      { name: "SOC2 Compliance", year: 2023, role: "Security Lead" },
      { name: "Security Audit Q4", year: 2022, role: "Pen Tester" },
      { name: "Zero Trust Implementation", year: 2024, role: "Security Architect" },
    ],
    seniorityLevel: "senior", yearsExperience: 8, avatarInitials: "OH",
    collaborators: ["emp-004", "emp-008"],
    technologies: ["Vault", "AWS IAM", "Burp Suite", "Snyk", "Terraform"],
    domainExpertise: ["Security Architecture", "Compliance", "Zero Trust"],
  },
  {
    id: "emp-012", name: "Freya Andersen", role: "Technical Writer",
    department: "Product",
    skills: ["Technical Writing", "API Documentation", "Developer Experience", "Content Strategy"],
    availability: "available", hourlyRate: 95, location: "Copenhagen",
    pastProjects: [
      { name: "API Docs Overhaul", year: 2023, role: "Lead Writer" },
      { name: "Developer Portal", year: 2024, role: "Content Strategist" },
      { name: "Internal Wiki Migration", year: 2022, role: "Technical Writer" },
    ],
    seniorityLevel: "mid", yearsExperience: 4, avatarInitials: "FA",
    collaborators: ["emp-002", "emp-010"],
    technologies: ["Markdown", "Docusaurus", "Notion", "Confluence"],
    domainExpertise: ["API Documentation", "Developer Experience", "Knowledge Management"],
  },
];

export const OVERLAPPING_PROJECTS: OverlappingProject[] = [
  {
    id: "overlap-001",
    name: "Finance Ops Automation",
    year: 2022,
    department: "Finance × Engineering",
    outcome: "completed",
    learnings: [
      "Built a shared data pipeline between finance and product analytics teams",
      "Established cross-functional standup cadence that reduced blockers by 40%",
      "Created reusable API integration patterns now used by 3 other teams",
    ],
    peopleInvolved: ["emp-001", "emp-003", "emp-007"],
    estimatedTimeSaved: "3 weeks",
  },
  {
    id: "overlap-002",
    name: "Platform Consolidation",
    year: 2023,
    department: "Platform Team",
    outcome: "stalled",
    learnings: [
      "Scope creep caused timeline to double — original brief was too broad",
      "Successfully migrated 2 of 5 planned services before pause",
      "Identified key dependency on legacy auth system that needs resolution",
    ],
    peopleInvolved: ["emp-001", "emp-004", "emp-006"],
    estimatedTimeSaved: "2 weeks",
  },
];
